---

- name: Configure - List required SAP Notes
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_sapnotes_versions | difference([''])

- name: Configure - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/{{ sap_note_line_item.number }}.yml"
  with_items: "{{ __sap_hana_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
