---

- name: Set kernel parameters
  ansible.builtin.lineinfile:
    path: "{{ __sap_general_preconfigure_etc_sysctl_sap_conf }}"
    create: yes
    mode: '0644'
    regexp: ^{{ line_item.name }}.*
    line: "{{ line_item.name }}={{ line_item.value }}"
    state: present
  with_items: "{{ sap_general_preconfigure_kernel_parameters }}"
  loop_control:
    loop_var: line_item

- name: Reload kernel parameters from file '{{ __sap_general_preconfigure_etc_sysctl_sap_conf }}'
  ansible.builtin.command: sysctl -p "{{ __sap_general_preconfigure_etc_sysctl_sap_conf }}"
  register: __sap_general_preconfigure_register_sap_conf_sysctl_p_output
  changed_when: true

- name: Display kernel parameters after setting kernel.pid_max
  ansible.builtin.debug:
    var: __sap_general_preconfigure_register_sap_conf_sysctl_p_output.stdout_lines
