---

- name: Copy file /etc/tmpfiles.d/sap.conf
  ansible.builtin.copy:
    src: etc/tmpfiles.d/sap.conf
    dest: /etc/tmpfiles.d/sap.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
