---
- name: Configure - Display SAP note number 2777782 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2777782$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2777782$') | first).version }}): SAP HANA settings for RHEL 8"

- ansible.builtin.import_tasks: 2777782/01-configure-selinux.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_01|d(false)

- ansible.builtin.import_tasks: 2777782/02-configure-tuned.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_02|d(false)

- ansible.builtin.import_tasks: 2777782/03-disable-abrt-coredumps-kdump.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_03|d(false)

- ansible.builtin.import_tasks: 2777782/04-turn-off-auto-numa-balancing.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_04|d(false)

- ansible.builtin.import_tasks: 2777782/05-disable-thp.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_05|d(false)

- ansible.builtin.import_tasks: 2777782/06-configure-c-states-for-lower-latency.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_06|d(false)

- ansible.builtin.import_tasks: 2777782/07-configure-cpu-governor.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_07|d(false)

- ansible.builtin.import_tasks: 2777782/08-configure-epb.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_08|d(false)

- ansible.builtin.import_tasks: 2777782/09-disable-ksm.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_09|d(false)

- ansible.builtin.import_tasks: 2777782/10-increase-pidmax.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_10|d(false)

- ansible.builtin.import_tasks: 2777782/11-enable-tsx.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2777782_11|d(false)
