---

- name: Configure - Display SAP note number 3119751 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).number }}
          (version {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).version }}): Linux Requirements for SAP Kernel 754 and for SAP Kernel 788 and higher"

- name: Get info about the compat-sap-c++-10.so file
  ansible.builtin.stat:
    path: /opt/rh/SAP/lib64/compat-sap-c++-10.so
  register: __sap_netweaver_preconfigure_register_stat_compat_sap_cpp

- name: Create directory '{{ sap_netweaver_preconfigure_rpath }}'
  ansible.builtin.file:
    path: "{{ sap_netweaver_preconfigure_rpath }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: __sap_netweaver_preconfigure_register_stat_compat_sap_cpp.stat.exists

- name: Create a link to '{{ sap_netweaver_preconfigure_rpath }}libstdc++.so.6'
  ansible.builtin.file:
    src: /opt/rh/SAP/lib64/compat-sap-c++-10.so
    dest: "{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6"
    state: link
  when: __sap_netweaver_preconfigure_register_stat_compat_sap_cpp.stat.exists
