---

- name: Configure 2772999-3
  ansible.builtin.debug:
    msg: "SAP note 2772999 Step 3: Configure Hostname"

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-hostname.yml
- ansible.builtin.import_tasks: ../../RedHat/generic/configure-etc-hosts.yml
- ansible.builtin.import_tasks: ../../RedHat/generic/check-dns-name-resolution.yml
