---

- name: Configure 2772999-10
  ansible.builtin.debug:
    msg: "SAP note 2772999 Step 10: Configure systemd-tmpfiles"

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-systemd-tmpfiles.yml
