---
__sap_general_preconfigure_sapnotes_versions:
  - ''

__sap_general_preconfigure_packages:
  - uuidd
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
# package hostname: needed by rhel-system-roles-sap
  - hostname

__sap_general_preconfigure_min_pkgs:
