---

# [A] Deduplicate values from /etc/hosts
- name: SAP HSR - Deduplicate values from /etc/hosts
  lineinfile:
    path: /etc/hosts
    create: false
    regexp: (?i)^\s*{{ item }}\s+
    state: absent
  loop:
    - "{{ sap_ha_install_hana_hsr_primary_ip }}"
    - "{{ sap_ha_install_hana_hsr_secondary_ip }}"

# [A] Edit /etc/hosts to add Node 1 and 2
- name: SAP HSR - [A] Edit /etc/hosts to add Node 1 and 2
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "{{ sap_ha_install_hana_hsr_primary_ip }}\t{{ sap_ha_install_hana_hsr_primary_hostname }}.{{ sap_ha_install_hana_hsr_fqdn }}\t{{ sap_ha_install_hana_hsr_primary_hostname }}"
    - "{{ sap_ha_install_hana_hsr_secondary_ip }}\t{{ sap_ha_install_hana_hsr_secondary_hostname }}.{{ sap_ha_install_hana_hsr_fqdn }}\t{{ sap_ha_install_hana_hsr_secondary_hostname }}"
