---

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- name: Assert that service numad is disabled, and inactive or stopped, if tuned is not to be used
  ansible.builtin.include_tasks: assert-services.yml
  vars:
    line_item: numad

  when: not sap_hana_preconfigure_use_tuned or
        sap_hana_preconfigure_assert_all_config|d(false)
