---

- name: Perform specific steps for tuned profile on RHEL 8.0 ppc64le
  block:

    - name: RHEL 8.0 ppc64le - Create directory /etc/tuned/sap-hana-ppc64le
      ansible.builtin.file:
        path: /etc/tuned/sap-hana-ppc64le
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: RHEL 8.0 ppc64le - Copy file /etc/tuned/sap-hana-ppc64le/tuned.conf
      ansible.builtin.copy:
        src: etc/tuned/sap-hana-ppc64le/tuned.conf
        dest: /etc/tuned/sap-hana-ppc64le/tuned.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

  when:
    - sap_hana_preconfigure_use_tuned
    - ansible_architecture == "ppc64le"
    - ansible_distribution_version == "8.0"

- name: Perform steps for setting tuned profile
  block:

    - name: Enable and start tuned
      ansible.builtin.service:
        name: tuned
        state: started
        enabled: yes

    - name: Get currently active tuned profile
      ansible.builtin.shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
      check_mode: no
      register: __sap_hana_preconfigure_register_current_tuned_profile
      changed_when: false

    - name: Display the output of the tuned-adm active command
      ansible.builtin.debug:
        var: __sap_hana_preconfigure_register_current_tuned_profile.stdout_lines, __sap_hana_preconfigure_register_current_tuned_profile.stderr_lines

    - name: Switch to tuned profile '{{ sap_hana_preconfigure_tuned_profile }}' if not currently active
      block:
        - name: Switch to tuned profile '{{ sap_hana_preconfigure_tuned_profile }}'
          ansible.builtin.command: /usr/sbin/tuned-adm profile '{{ sap_hana_preconfigure_tuned_profile }}'
          changed_when: true

        - name: Show new active tuned profile
          ansible.builtin.shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
          check_mode: no
          register: __sap_hana_preconfigure_register_new_tuned_profile
          changed_when: false

        - name: Display the output of the tuned-adm active command after switching to profile '{{ sap_hana_preconfigure_tuned_profile }}'
          ansible.builtin.debug:
            var: __sap_hana_preconfigure_register_new_tuned_profile.stdout_lines, __sap_hana_preconfigure_register_new_tuned_profile.stderr_lines

      when:
        - __sap_hana_preconfigure_register_current_tuned_profile.stdout != sap_hana_preconfigure_tuned_profile

  when:
    - sap_hana_preconfigure_use_tuned
