---

- name: Configure - Display SAP note number 2002167 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2002167$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2002167$') | first).version }}): Configure RHEL 7"

- ansible.builtin.import_tasks: 2002167/02-configuration-changes.yml
  when: sap_general_preconfigure_config_all|d(true) or sap_general_preconfigure_2002167_02|d(false)

- ansible.builtin.import_tasks: 2002167/03-setting-the-hostname.yml
  when: sap_general_preconfigure_config_all|d(true) or sap_general_preconfigure_2002167_03|d(false)

- ansible.builtin.import_tasks: 2002167/04-linux-kernel-parameters.yml
  when: sap_general_preconfigure_config_all|d(true) or sap_general_preconfigure_2002167_04|d(false)

- ansible.builtin.import_tasks: 2002167/05-process-resource-limits.yml
  when: sap_general_preconfigure_config_all|d(true) or sap_general_preconfigure_2002167_05|d(false)

- ansible.builtin.import_tasks: 2002167/06-additional-notes-for-installing-sap-systems.yml
  when: sap_general_preconfigure_config_all|d(true) or sap_general_preconfigure_2002167_06|d(false)
