---

- name: "SAP Pacemaker Setup - Resource default update"
  ansible.builtin.set_fact:
    sap_ha_set_hana_resource_defaults: ""
  when: ansible_distribution_version == "8.2"

# [1] Setup HANA HA resource-stickiness
- name: "SAP Pacemaker Setup - [1] Update default values"
  tags: pacemaker
  shell: |
    pcs resource defaults {{ sap_ha_set_hana_resource_defaults }} resource-stickiness=1000

# [1] Setup HANA HA migration-threshold
- name: "SAP Pacemaker Setup - [1] Update default values"
  tags: pacemaker
  shell: |
    pcs resource defaults {{ sap_ha_set_hana_resource_defaults }} migration-threshold=5000

# [1] Check Resources topology
- name: "SAP Pacemaker Setup - [1] Check SAP HANA Resources Topology"
  tags: pacemaker
  shell: |
    pcs resource config SAPHanaTopology_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }} 
  register: sap_ha_set_hana_check_resource_topology
  failed_when: false
  changed_when: false

# [1] Setup HANA HA SAP HANA Resource Topology
- name: "SAP Pacemaker Setup - [1] Create SAP HANA Resource Topology"
  debugger: on_failed
  tags: pacemaker
  shell: |
    pcs resource create \
    SAPHanaTopology_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }} \
    SAPHanaTopology SID={{ sap_ha_set_hana_sid }} \
    InstanceNumber={{ sap_ha_set_hana_instance_number }} \ 
    op start timeout=600 op stop timeout=600 op monitor interval=10 timeout=600 \
    clone clone-max=2 clone-node-max=1 interleave=true
  register: pcs_cluster_create_SAPHanaTopology_resource
  when:
     - sap_ha_set_hana_check_resource_topology.rc == 1

# [1] Check Resources SAPHana
- name: "SAP Pacemaker Setup - [1] Check SAP HANA Resources Hana"
  tags: pacemaker
  shell: |
    pcs resource config SAPHana_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}
  register: sap_ha_set_hana_check_resource_hana
  failed_when: false
  changed_when: false

# [1] Setup HANA HA SAP HANA Resource HANA
- name: "SAP Pacemaker Setup - [1] Create SAP HANA Resource HANA"
  tags: pacemaker
  shell: |
    pcs resource create \
    SAPHana_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }} \
    SAPHana SID={{ sap_ha_set_hana_sid }} \
    InstanceNumber={{ sap_ha_set_hana_instance_number }} \ 
    PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=900 AUTOMATED_REGISTER=true \
    op start timeout=3600 op stop timeout=3600 \
    op monitor interval=121 role="Slave" timeout=700 \
    op monitor interval=119 role="Master" timeout=700 \
    op promote timeout=3600 \
    op demote timeout=3600 \
    promotable notify=true \
    clone-max=2 clone-node-max=1 interleave=true 
  register: pcs_cluster_create_SAPHana_resource
  when:
     - sap_ha_set_hana_check_resource_hana.rc == 1

# [1] Check Resources
- name: "SAP Pacemaker Setup - [1] Check SAP HANA Resources VIP"
  tags: pacemaker
  shell: |
    pcs resource config vip_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}_MASTER 
  register: sap_ha_set_hana_check_resource_vip
  when: sap_ha_set_hana_vip1 is defined
  failed_when: false
  changed_when: false

# [1] Setup HANA HA SAP HANA Resource HANA
- name: "SAP Pacemaker Setup - [1] Create SAP HANA Resource HANA"
  tags: pacemaker
  shell: |
    pcs resource create \
    vip_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}_MASTER \
    IPaddr2 ip="{{ sap_ha_set_hana_vip1 }}" 
  register: pcs_cluster_create_SAPHana_resource
  when:
     - sap_ha_set_hana_check_resource_vip.rc == 1

# [1] Start Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Start Pacemaker cluster
  tags: pacemaker
  shell: |
    pcs cluster start --all
  register: pcs_cluster_start_reg

# [1] Check Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Check Pacemaker cluster
  shell: |
    pcs status
  register: pcs_status_reg
