---

- name: SAP Pacemaker Part 3 - Sudoer Configuration
  include_tasks: cluster_sudoer.yml
  tags:
    - pacemaker

- name: SAP Pacemaker Part 3 - Resource Configuration
  include_tasks: cluster_resources.yml
  tags:
    - pacemaker
  when:
    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname

- name: "SAP Pacemaker Part 4 - srhooks Configuration"
  include_tasks: cluster_srhook.yml
  tags:
    - srhook

- name: SAP Pacemaker Part 5 - Constraints Configuration
  include_tasks: cluster_constraint.yml
  tags:
    - constraint
