---

- name: SAP HANA HA - Disable Firewall
  include_tasks: disable_firewall.yml

# Part 1 obsolete done by cluster_srhook.yml
#- name: SAP HANA HA - SAPHanaSR python hook
#  include_tasks: saphanasr_python_hook.yml
#  when:
#    - sap_ha_set_hana_part == '1'

- name: SAP Pacemaker Part 3 - Sudoer Configuration
  include_tasks: cluster_sudoer.yml
  tags:
    - pacemaker

- name: SAP Pacemaker Part 3 - Resource Configuration
  include_tasks: cluster_resources.yml
  tags:
    - pacemaker
  when:
    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname

- name: "SAP Pacemaker Part 4 - srhooks Configurationi"
  include_tasks: cluster_srhook.yml
  tags:
    - srhook

- name: SAP Pacemaker Part 5 - Constraints Configuration
  include_tasks: cluster_constraint.yml
  tags:
    - constraint
