---

# Part 1
- name: Prepare NW for Installation
  include_tasks: prepare.yml
  when:
    - sap_ha_set_netweaver_part == '1'

# Part 2
- name: Post NW ASCS Installation
  include_tasks: post_ascs.yml
  when:
    - sap_ha_set_netweaver_part == '2'

# Part 3
- name: Post NW ERS Installation
  include_tasks: post_ers.yml
  when:
    - sap_ha_set_netweaver_part == '3'

# Part 4
- name: Post NW PAS Installation
  include_tasks: post_pas.yml
  when:
    - sap_ha_set_netweaver_part == '4'
