---

# Generic Install

- name: SAP SWPM Pre Install - Generic Install
  set_fact:
    sap_swpm_sum_prepare: 'true'
    sap_swpm_sum_start: 'true'
    sap_swpm_spam_update: 'false'
    sap_swpm_spam_update_sar:
    sap_swpm_configure_tms: 'true'
    sap_swpm_tmsadm_password: "{{ sap_swpm_master_password }}"
#    sap_swpm_sum_batch_file: "/software/swpm20/ConfigInput.xml"

# 0. MP Stack

# - name: SAP SWPM Pre Install - Fresh Install - Get MP Stack xml from {{ sap_swpm_software_path }}
#   shell: |
#     ls MP_Stack_*
#   args:
#     chdir: "{{ sap_swpm_software_path }}"
#   register: sap_swpm_mp_stack_file_get

# - name: SAP SWPM Pre Install - Set fact for MP Stack
#   set_fact:
#     sap_swpm_mp_stack_path: "{{ sap_swpm_software_path }}"
#     sap_swpm_mp_stack_file_name: "{{ sap_swpm_mp_stack_file_get.stdout }}"
#  when: "sap_swpm_mp_stack_file_get.exists"
