---

# required SAP Notes for SLES 15

__sap_netweaver_preconfigure_sapnotes:
  - "1275776"

__sap_netweaver_preconfigure_packages:
  - libstdc++6
  - libatomic1
  - libgcc_s1
  - libltdl7
  - insserv
  - cpupower
  - hicolor-icon-theme
  - libcpupower0
  - libsensors4
  - patterns-base-basesystem
  - patterns-server-enterprise-sap_server
  - patterns-yast-yast2_basis
  - procmail
  - saptune
  - sysstat
  - system-user-uuidd
  - uuidd
  - yast2-auth-client
  - yast2-auth-server
  - yast2-theme
  - yast2-vpn
  - tcsh
  - acl

__sap_netweaver_preconfigure_min_swap_space_mb: '20480'
