---

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- name: Assert 2777782-4
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 4: Turn off auto-numa balancing"
- import_tasks: ../../RedHat/generic/assert-auto-numa-balancing.yml
