---

- name: Configure 2002167-2a
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 2a: Configure the Firewall"

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-firewall.yml

- name: Configure 2002167-2b
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 2b: Configure SELinux"

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-selinux.yml
