---

- name: Assert 2002167-3
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 3: Setting the Hostname"

- ansible.builtin.import_tasks: ../../RedHat/generic/assert-hostname.yml
- ansible.builtin.import_tasks: ../../RedHat/generic/assert-etc-hosts.yml
- ansible.builtin.import_tasks: ../../RedHat/generic/assert-dns-name-resolution.yml
