---

- name: Configure 2002167-4
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 4: Linux Kernel Parameters"

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-kernel-parameters.yml
