---

- name: Assert 2002167-5
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 5: Process Resource Limits"

- ansible.builtin.import_tasks: ../../RedHat/generic/assert-limits-conf-file.yml
- ansible.builtin.import_tasks: ../../RedHat/generic/assert-nproc-limits.yml
