---

- name: Configure 2002167-6
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 6: Additional notes for installing SAP systems"

- name: Link LDAP library libldap
  ansible.builtin.file:
    src: /usr/lib64/libldap-2.3.so.0
    dest: /usr/lib64/libldap.so.199
    state: link

- name: Link LDAP library liblber
  ansible.builtin.file:
    src: /usr/lib64/liblber-2.3.so.0
    dest: /usr/lib64/liblber.so.199
    state: link

- ansible.builtin.import_tasks: ../../RedHat/generic/configure-systemd-tmpfiles.yml
