---

# [1] Setup Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Setup Pacemaker cluster
  shell: |
    pcs cluster setup \
    {{ sap_ha_install_pacemaker_cluster_name }} {{ sap_ha_install_pacemaker_node1_hostname }} {{ sap_ha_install_pacemaker_node2_hostname }} \
    totem token=30000 --force
  register: pcs_cluster_setup_reg

# [1] Start Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Start Pacemaker cluster
  shell: |
    pcs cluster start --all
  register: pcs_cluster_start_reg

# [1] Check Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Check Pacemaker cluster
  shell: |
    pcs status
  register: pcs_status_reg

# [A] Set Expected Votes
- name: SAP Pacemaker Setup - [1] Set Expected Votes
  shell: |
    pcs quorum expected-votes 2
  register: pcs_quorum_expected_votes_reg

# [1] Allow concurrent fence actions
- name: SAP Pacemaker Setup - [1] Allow concurrent fence actions
  shell: |
    pcs property set concurrent-fencing=true
