---

# [A] - runs on both node 1 and 2 / primary secondary
# [1] - runs on node 1 / primary
# [2] - runs on node 2 / secondary

- name: Rename some variables used by hdblcm configfile
  ansible.builtin.set_fact:
    sap_ha_install_pacemaker_hana_sid: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_hana_sid)|d('RH1') }}"
    sap_ha_install_pacemaker_site1_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site1_name)|d('DC1') }}"
    sap_ha_install_pacemaker_site2_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site2_name)|d('DC2') }}"
    sap_ha_install_pacemaker_site3_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site3_name)|d('DC3') }}"
    sap_ha_install_pacemaker_site4_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site4_name)|d('DC4') }}"
    sap_ha_install_pacemaker_node1_hostname: "{{ hana_node1_hostname|d(sap_ha_install_pacemaker_node1_hostname)|d('hana01') }}"
    sap_ha_install_pacemaker_node2_hostname: "{{ hana_node2_hostname|d(sap_ha_install_pacemaker_node2_hostname)|d('hana02') }}"
    sap_ha_install_pacemaker_instance_number: "{{ sap_hana_instance_number|d(sap_ha_install_pacemaker_instance_number)|d('00') }}"
  tags:
    - pacemaker
    - ha
# [A] Disable firewall

- name: SAP Pacemaker Setup - [A] Disable firewall
  include_tasks: disable_firewall.yml
  
# Part 1
# Installs the necessary software and preconfiguration

- name: "SAP Pacaemaker - Check pcs"
  shell: |
      rpm -qa pcs
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_install_pacemaker_check_pcs
  changed_when: '"pcs" in sap_ha_install_pacemaker_check_pcs.stdout'

- name: "SAP Pacemaker Part 1 - Software Setup"
  include_tasks: software_setup.yml
  when:
    - sap_ha_install_pacemaker_check_pcs.rc != '0'
#    - sap_ha_install_pacemaker_part == '1'

- name: SAP Pacemaker Part 1 - Preconfig
  include_tasks: preconfig.yml
#  when:
#    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname
#    - sap_ha_install_pacemaker_part == '1'

# Part 2
# Cluster Setup, Service Principal, Stonith Configuration

- name: "SAP Pacemaker Part 2 - Check Cluster"
  tags: pacemaker
  shell: |
      pcs cluster config
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_install_pacemaker_check_cluster
  changed_when: false # '"Cluster Name" in sap_ha_install_pacemaker_check_cluster.stdout'
  failed_when: false
  
- name: "SAP Pacemaker Part 2- Debug Check cluster"
  debug:
    var: sap_ha_install_pacemaker_check_cluster
  tags: pacemaker

- name: SAP Pacemaker Part 2 - Cluster Setup
  include_tasks: cluster_setup.yml
  when:
    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname
    - sap_ha_install_pacemaker_check_cluster.rc == 1

- name: SAP Pacemaker Part 2 - Stonith Configuration
  include_tasks: stonith_config.yml
  when:
    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname

- name: SAP Pacemaker Part 3 - Sudoer Configuration
  include_tasks: cluster_sudoer.yml
  tags:
    - pacemaker

- name: SAP Pacemaker Part 3 - Resource Configuration
  include_tasks: cluster_resources.yml
  tags:
    - pacemaker
  when:
    - ansible_nodename == sap_ha_install_hana_hsr_primary_hostname

- name: "SAP Pacemaker Part 4 - srhooks Configurationi"
  include_tasks: cluster_srhook.yml
  tags:
    - srhook

- name: SAP Pacemaker Part 5 - Constraints Configuration
  include_tasks: cluster_constraint.yml
  tags:
    - constraint
