---

# [1] Create the STONITH devices
- name: Create the STONITH devices
  shell: |
    pcs property set stonith-timeout=900
  register: pcs_property_set_stonith_timeout
  when:
    - sap_ha_install_pacemaker_role == 'primary'

# [1] Configure the fence device
- name: Configure the fence device
  shell: |
    pcs stonith create rsc_st_azure fence_azure_arm \
    username="{{ sap_ha_install_pacemaker_client_id }}" password="{{ sap_ha_install_pacemaker_client_secret }}" \
    resourceGroup="{{ sap_ha_install_pacemaker_resource_group }}" tenantId="{{ sap_ha_install_pacemaker_tenant_id }}" \
    subscriptionId="{{ sap_ha_install_pacemaker_subscription_id }}" \
    pcmk_host_map="{{ sap_ha_install_pacemaker_node1_hostname }}:{{ sap_ha_install_pacemaker_node1_hostname }};{{ sap_ha_install_pacemaker_node2_hostname }}:{{ sap_ha_install_pacemaker_node2_hostname }}" \
    power_timeout=240 pcmk_reboot_timeout=900 pcmk_monitor_timeout=120 pcmk_monitor_retries=4 pcmk_action_limit=3 pcmk_delay_max=15 \
    op monitor interval=3600
  register: pcs_stonith_create
  when:
    - sap_ha_install_pacemaker_role == 'primary'
    - sap_ha_install_pacemaker_stonith_fence_agent == 'fence-agents-azure-arm'
#     pcmk_host_map="prod-cl1-0:prod-cl1-0-{{ sap_hana_ha_pacemaker_node1_hostname }};prod-cl1-1:prod-cl1-1-{{ sap_hana_ha_pacemaker_node2_hostname }}" \

# [1] Configure the fence device
- name: Configure the rhevm fence device
  shell: |
    pcs stonith create {{ sap_ha_install_pacemaker_stonith_name }} {{ sap_ha_install_pacemaker_stonith_fence_agent }} \
    disable_http_filter=1 {{ sap_ha_install_pacemaker_stonith_credential }} \
    pcmk_host_map="{{ sap_ha_install_pacemaker_stonith_pcmk_host_map }}" \
    power_wait=3 ssl=1 ssl_insecure=1
  register: pcs_stonith_rhevm_create
  when:
    - sap_ha_install_pacemaker_role == 'primary'
    - sap_ha_install_pacemaker_stonith_fence_agent == 'fence_rhevm'

# [1] Enable the use of a STONITH device
- name: Create the STONITH devices
  shell: |
    pcs property set stonith-enabled=true
  register: pcs_property_set_stonith_enabled
  when:
    - sap_ha_install_pacemaker_role == 'primary'
