---

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never"
- name: Assert 2292690-3
  ansible.builtin.debug:
    msg: "SAP note 2292690 Step 3: Disable Transparent Hugepages (THP)"
- import_tasks: ../../RedHat/generic/assert-thp.yml
