---

# can be configured by tuned profile sap-hana, entry "energy_perf_bias=performance"
#   in included tuned profile throughput-performance
- name: Assert 2292690-6
  ansible.builtin.debug:
    msg: "SAP note 2292690 Step 6: Configure Energy Performance Bias (EPB, x86_64 platform only)"
- import_tasks: ../../RedHat/generic/assert-epb.yml
