---
#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
# Reason for noqa: Both yum and dnf support "state: latest"
- name: Ensure that the system is updated to the latest patchlevel # noqa package-latest
  ansible.builtin.package:
    state: latest
    name: "*"
  when: sap_hana_preconfigure_update | bool

- name: Ensure saphana pattern is installed
  community.general.zypper:
    type: pattern
    name: sap-hana
    state: present
    force: yes

- name: Ensure saptune is installed
  community.general.zypper:
    type: package
    name: "saptune={{ sap_hana_preconfigure_saptune_version }}"
    state: present
    force: yes
