---
- name: "SAP Pacemaker Setup -[A] check pcsd"
  ansible.builtin.shell: |
        systemctl is-active pcsd.service
  register: sap_ha_install_pacemaker_pcsd_active
  changed_when: false
  failed_when: false
  

# [A] Change hacluster password
- name: SAP Pacemaker Setup - [A] Ensure password for hacluster is configured
  ansible.builtin.shell: |
        echo '{{ sap_ha_install_pacemaker_hacluster_password }}' | passwd --stdin hacluster

# # [A] Change hacluster password
# - name: Ensure password for hacluster is configured
#   ansible.builtin.user:
#     name: hacluster
#     password: "{{ sap_ha_install_pacemaker_hacluster_password | password_hash('sha512') }}"

# [A] Enable basic cluster services
- name: SAP Pacemaker Setup - [A] Enable basic cluster services
  ansible.builtin.systemd: 
    name: pcsd.service
    state: started
    enabled: yes
  become: true
  when:
    - sap_ha_install_pacemaker_pcsd_active.rc != 0

# [A] Update /etc/hosts

# - name: SAP Pacemaker Setup - [A] Update /etc/hosts
#   include_tasks: update_etchosts.yml
