---

- name: SAP Media Check - SAP SWPM - Set fact for install media directory
  set_fact:
    sap_swpm_software_path: "{{ sap_install_media_detect_directory }}"
    sap_swpm_sapcar_path: "{{ sap_install_media_detect_directory }}/sap_swpm"
    sap_swpm_swpm_path: "{{ sap_install_media_detect_directory }}/sap_swpm"

- name: SAP Media Check - SAP SWPM - Check availability of software path - {{ sap_swpm_software_path }}
  stat:
    path: "{{ sap_swpm_software_path }}"
  register: sap_swpm_software_path_stat
  failed_when: not sap_swpm_software_path_stat.stat.exists

- name: SAP Media Check - SAP SWPM - Change ownership of software path - {{ sap_swpm_software_path }}
  ansible.builtin.file:
    path: "{{ sap_swpm_software_path }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: root
    group: root

- name: SAP Media Check - SAP SWPM - Detect Installation Software
  include_tasks: swpm/detect_swpm.yml
