---

- name: SAP Media Check - SAP HANA - Set fact for install media directory
  set_fact:
    sap_hana_install_directory: "{{ sap_install_media_detect_directory }}/sap_hana"

- name: SAP Media Check - SAP HANA - Check availability of software path - {{ sap_hana_install_directory }}
  stat:
    path: "{{ sap_hana_install_directory }}"
  register: sap_hana_install_software_path_stat
  failed_when: not sap_hana_install_software_path_stat.stat.exists

- name: SAP Media Check - SAP HANA - Change ownership of software path - {{ sap_hana_install_directory }}
  ansible.builtin.file:
    path: "{{ sap_hana_install_directory }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: root
    group: root

- name: SAP Media Check - SAP HANA - Prepare
  include_tasks: hana/prepare_hana.yml
