---

- name: SAP Media Detect - Organize HANA
  include_tasks: "organize_hana.yml"

- name: SAP Media Detect - Organize SWPM
  include_tasks: "organize_swpm.yml"

- name: SAP Media Detect - Check HANA
  include_tasks: "check_hana.yml"

- name: SAP Media Detect - Check SWPM
  include_tasks: "check_swpm.yml"

- name: SAP Media Detect - Display Paths
  debug:
    msg:
      - "SWPM Software Path - {{ sap_swpm_software_path }}"
      - "SWPM SAPCAR Path - {{ sap_swpm_sapcar_path }}"
      - "SWPM Path - {{ sap_swpm_swpm_path }}"
      - "SAP HANA Path - {{ sap_hana_install_directory }}"
