---

- name: SAP Media Organize - SAP HANA - Create Directory - {{ sap_install_media_detect_directory }}/sap_hana
  file:
    path: "{{ sap_install_media_detect_directory }}/sap_hana"
    state: directory
    mode: '0755'
    owner: root
    group: root

# IMDB SAR Files
- name: SAP Media Organize - SAP HANA - Get all IMDB SAR files in folder - {{ sap_install_media_detect_directory }}
  shell: |
    ls IMDB*.SAR
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
  register: imdb_sarfiles_list

- name: SAP Media Organize - SAP HANA - Set fact list of SAR files
  set_fact:
    sap_hana_install_imdb_sar: "{{ imdb_sarfiles_list.stdout.split() }}"
  when:
    - not( imdb_sarfiles_list.stdout == '' )

- name: SAP Media Organize - SAP HANA - Copy SAP HANA files
  shell: |
    cp {{ sap_install_media_detect_directory }}/{{ item }} {{ sap_install_media_detect_directory }}/sap_hana/{{ item }}
  loop: "{{ sap_hana_install_imdb_sar }}"
  when:
    - not( imdb_sarfiles_list.stdout == '' )

# SAPCAR
- name: SAP Media Organize - SAP HANA - Get SAPCAR executable file from folder - {{ sap_install_media_detect_directory }}
  shell: |
    ls SAPCAR*.EXE
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
  register: sapcar_executable

- name: SAP Media Organize - SAP HANA - Copy SAPCAR file
  shell: |
    cp {{ sap_install_media_detect_directory }}/{{ sapcar_executable.stdout }} {{ sap_install_media_detect_directory }}/sap_hana/{{ sapcar_executable.stdout }}

# SAPHOSTAGENT
- name: SAP Media Organize - SAP HANA - Get SAPHOSTAGENT SAR file from folder - {{ sap_install_media_detect_directory }}
  shell: |
    ls SAPHOSTAGENT*SAR
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
  register: saphostagent_sarfile

- name: SAP Media Organize - SAP HANA - Copy SAPHOSTAGENT SAR file
  shell: |
    cp {{ sap_install_media_detect_directory }}/{{ saphostagent_sarfile.stdout }} {{ sap_install_media_detect_directory }}/sap_hana/{{ saphostagent_sarfile.stdout }}
