---

# Remove Existing inifile.params
- name: SAP SWPM advanced mode - Create inifile.params
  file:
    path: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    state: touch

- name: SAP SWPM advanced mode - Loop over the dictionary and output to file
  lineinfile:
    path: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    state: present
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ sap_swpm_inifile_custom_values_dictionary }}"

# NOTE: Values in Dictionary Keys for instance numbers must be string using '01' single quote, otherwise SAP SWPM will crash


# Detect variables from generated inifile
- name: SAP SWPM advanced mode - Detect Variables
  include_tasks: detect_variables.yml

# Prepare Software
- name: SAP SWPM advanced mode - Prepare Software
  include_tasks: prepare_software.yml
