---

# Execute common pre installation tasks
- import_tasks: common_pre.yml

# Deploy SAPHOSTAGENT using RPM file
- import_tasks: deploy_rpm.yml
  when: sap_hostagent_installation_type == "rpm"

# Deploy SAPHOSTAGENT using SAR file
- import_tasks: deploy_sar.yml
  when: sap_hostagent_installation_type == "sar"

 # Deploy SAPHOSTAGENT using SAR file existing on system
- import_tasks: deploy_sar_remote.yml
  when: sap_hostagent_installation_type == "sar-remote"

# Deploy SAPHOSTAGENT using SAP Installation Bundle
- import_tasks: deploy_bundle.yml
  when: sap_hostagent_installation_type == "bundle"

# Configuring SSL for SAP Host Agent
- import_tasks: config_ssl.yml
  when: sap_hostagent_config_ssl

# Execute common post installation tasks
- import_tasks: common_post.yml
