---
- hosts: all
  become: true
  vars:
          sap_hana_preconfigure_fail_if_reboot_required: no
          sap_hana_preconfigure_update: yes
  roles:
    - { role: community.sap_install.sap_hana_preconfigure }
